# Generated by Django 3.1.2 on 2020-11-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201122_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='first_name',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='last_name',
            new_name='contact_last_name',
        ),
    ]
